/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

//Programmed by Fajar Windhu Zulfikar
//FB: @fajarwzulfikar, IG: @fajarwz

//the algorithm is bad, this app is still not finished either, but it can 
//implement a simple enough CRUD with login system

package sipijar;

import java.sql.Connection;
//import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
//import java.util.Calendar;
//import javax.swing.JMenuBar;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import javax.swing.JDialog;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
/*import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
*/
public class Buat_Permohonan extends javax.swing.JFrame {

    Connection con;
    Statement stat;
    ResultSet rs;
    String sql;
    
    public Buat_Permohonan() {
        initComponents();
    }
    
    public Buat_Permohonan(String passid,String passnama){
        initComponents();
        
        idPeminjamField.setText(passid);
        namaPeminjamField.setText(passnama);
        //System.out.println(dateFormat.format(date)); //2018/12/07
        load_table();
        tampil_combo();
        kosong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane2 = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        idPeminjamLabel = new javax.swing.JLabel();
        idPeminjamField = new javax.swing.JTextField();
        namaPeminjamLabel = new javax.swing.JLabel();
        namaPeminjamField = new javax.swing.JTextField();
        namaRuanganLabel = new javax.swing.JLabel();
        namaRuanganCombo = new javax.swing.JComboBox<>();
        kebutuhanLabel = new javax.swing.JLabel();
        kebutuhanField = new javax.swing.JTextField();
        tanggalPinjamLabel = new javax.swing.JLabel();
        tanggalPinjamField = new javax.swing.JTextField();
        waktuPinjamLabel = new javax.swing.JLabel();
        waktuPinjamField = new javax.swing.JTextField();
        kapasitasPinjamLabel = new javax.swing.JLabel();
        kapasitasPinjamField = new javax.swing.JTextField();
        tanggalDibuatLabel = new javax.swing.JLabel();
        tanggalDibuatField = new javax.swing.JTextField();
        idPeminjamanLabel = new javax.swing.JLabel();
        idPeminjamanField = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();
        statusField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelMahasiswa = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        clearButton = new javax.swing.JButton();
        tambahButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        mahasiswaMenuBar = new javax.swing.JMenuBar();
        lihatPeminjamanMenu = new javax.swing.JMenu();
        exitMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIPIJAR - Lihat Peminjaman");
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(128, 128, 128)), "Permohonan Peminjaman Ruangan", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N

        idPeminjamLabel.setText("ID Peminjam");

        idPeminjamField.setEditable(false);
        idPeminjamField.setBackground(new java.awt.Color(204, 204, 204));
        idPeminjamField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPeminjamFieldActionPerformed(evt);
            }
        });

        namaPeminjamLabel.setText("Nama Peminjam");

        namaPeminjamField.setEditable(false);
        namaPeminjamField.setBackground(new java.awt.Color(204, 204, 204));

        namaRuanganLabel.setText("Nama Ruangan");

        namaRuanganCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --" }));

        kebutuhanLabel.setText("Kebutuhan");

        tanggalPinjamLabel.setText("Tanggal Dipinjam");

        waktuPinjamLabel.setText("Waktu Pinjam");

        kapasitasPinjamLabel.setText("Kapasitas Pinjam");

        tanggalDibuatLabel.setText("Tanggal Dibuat");

        tanggalDibuatField.setEditable(false);
        tanggalDibuatField.setBackground(new java.awt.Color(204, 204, 204));

        idPeminjamanLabel.setText("ID Peminjaman");

        idPeminjamanField.setEditable(false);
        idPeminjamanField.setBackground(new java.awt.Color(204, 204, 204));

        statusLabel.setText("Status");

        statusField.setEditable(false);
        statusField.setBackground(new java.awt.Color(204, 204, 204));

        tabelMahasiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelMahasiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMahasiswaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelMahasiswa);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(128, 128, 128)));
        jPanel2.setPreferredSize(new java.awt.Dimension(360, 30));

        clearButton.setText("Baru");
        clearButton.setPreferredSize(new java.awt.Dimension(55, 25));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        tambahButton.setText("Tambah");
        tambahButton.setPreferredSize(new java.awt.Dimension(67, 25));
        tambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahButtonActionPerformed(evt);
            }
        });

        editButton.setText("Update");
        editButton.setPreferredSize(new java.awt.Dimension(51, 25));
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tambahButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(namaRuanganLabel)
                                    .addComponent(idPeminjamLabel)
                                    .addComponent(idPeminjamanLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(idPeminjamanField)
                                    .addComponent(idPeminjamField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(namaRuanganCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tanggalPinjamLabel)
                                    .addComponent(kapasitasPinjamLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(kapasitasPinjamField, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(tanggalPinjamField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(namaPeminjamLabel)
                                .addGap(9, 9, 9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(waktuPinjamLabel)
                                    .addComponent(kebutuhanLabel)
                                    .addComponent(tanggalDibuatLabel)
                                    .addComponent(statusLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(statusField)
                            .addComponent(waktuPinjamField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(kebutuhanField)
                            .addComponent(namaPeminjamField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(tanggalDibuatField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idPeminjamLabel)
                            .addComponent(idPeminjamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaRuanganLabel)
                            .addComponent(namaRuanganCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tanggalPinjamLabel)
                            .addComponent(tanggalPinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kapasitasPinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kapasitasPinjamLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaPeminjamLabel)
                            .addComponent(namaPeminjamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kebutuhanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kebutuhanLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(waktuPinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(waktuPinjamLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tanggalDibuatLabel)
                            .addComponent(tanggalDibuatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idPeminjamanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idPeminjamanLabel)
                    .addComponent(statusLabel)
                    .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        lihatPeminjamanMenu.setText("Lihat Peminjaman");
        mahasiswaMenuBar.add(lihatPeminjamanMenu);

        exitMenu.setText("Exit");
        exitMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMenuMouseClicked(evt);
            }
        });
        mahasiswaMenuBar.add(exitMenu);

        setJMenuBar(mahasiswaMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        try{
            //UPDATE `members` SET `contact_number` = '0759 253 542' WHERE `membership_number` = 1;
            String sql = "UPDATE t_peminjaman SET id_peminjam = '"+idPeminjamField.getText()+"',"+
                    " nama_peminjam = '"+namaPeminjamField.getText()+"',"+
                    " nama_ruangan = '"+namaRuanganCombo.getSelectedItem()+"',"+
                    " tgl_pinjam = '"+tanggalPinjamField.getText()+"',"+
                   " waktu_pinjam = '"+waktuPinjamField.getText()+"',"+
                    " kebutuhan_pinjam = '"+kebutuhanField.getText()+"',"+
                    " kapasitas_pinjam = '"+kapasitasPinjamField.getText()+"'"+
                    " WHERE id_peminjaman = '"+idPeminjamanField.getText()+"'";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            jOptionPane2.showMessageDialog(null, "Data Berhasil Diupdate");
            
            pst.close();
            conn.close();
        }
        catch(Exception e){
            jOptionPane2.showMessageDialog(null, "Perubahan Data Gagal "+e.getMessage());
        }
        load_table();
        kosong();
    }//GEN-LAST:event_editButtonActionPerformed

    private void tambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahButtonActionPerformed
        try{
            /*String myDriver = "org.gjt.mm.mysql.Driver";
            String myUrl = "jdbc:mysql://localhost/sipijar";
            Class.forName(myDriver);
            Connection conn = DriverManager.getConnection(myUrl, "root", "");
            
            String query = "INSERT INTO mhs (id_peminjam,nama_peminjam,nama_ruangan,tgl_pinjam,waktu_pinjam,kebutuhan_pinjam,kapasitas_pinjam) VALUES ('"+
                    idPeminjamField.getText()+"','"+namaPeminjamField.getText()+"','"+namaRuanganField.getText()+"','"+tanggalPinjamField.getText()+
                    "','"+waktuPinjamField.getText()+"','"+kebutuhanField.getText()+"','"+
                    kapasitasPinjamField.getText()+"')";
            // create the mysql insert preparedstatement
            PreparedStatement preparedStmt = conn.prepareStatement(query);
            // execute the preparedstatement
            ResultSet rs = preparedStmt.executeQuery();*/
            //(id_peminjam,nama_peminjam,nama_ruangan,tgl_pinjam,waktu_pinjam,kebutuhan_pinjam,kapasitas_pinjam) 
            
            //sql
            String sql = "INSERT INTO t_peminjaman (id_peminjam,nama_peminjam,tgl_post,nama_ruangan,tgl_pinjam,waktu_pinjam,kebutuhan_pinjam,kapasitas_pinjam,status) VALUES ('"+
                    idPeminjamField.getText()+"','"+namaPeminjamField.getText()+"',"+"CURDATE()"+",'"+namaRuanganCombo.getSelectedItem()+"','"+tanggalPinjamField.getText()+
                    "','"+waktuPinjamField.getText()+"','"+kebutuhanField.getText()+"','"+
                    kapasitasPinjamField.getText()+"','Belum Disetujui')";
            //konek ke DB
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            //pop-up berhasil
            jOptionPane2.showMessageDialog(null, "Penyimpanan Data Berhasil");
            load_table();
            kosong();
            pst.close();
            conn.close();
            
            /*jOptionPane2.showMessageDialog(null, "Penyimpanan Data Berhasil");
            load_table();
            kosong();
            preparedStmt.close();
            conn.close();*/
        } 
        catch (Exception e) {
            //pop-up error
            jOptionPane2.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_tambahButtonActionPerformed

    private void idPeminjamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPeminjamFieldActionPerformed
        
    }//GEN-LAST:event_idPeminjamFieldActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        kosong();
    }//GEN-LAST:event_clearButtonActionPerformed

    private void tabelMahasiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMahasiswaMouseClicked
        //menampilkan data ke dalam form pengisian
        int baris = tabelMahasiswa.rowAtPoint(evt.getPoint());  //tanda perbaris
        String currID = idPeminjamField.getText(); //identifikasi id user
        String idPeminjam = tabelMahasiswa.getValueAt(baris, 1).toString(); //id peminjam di data tertentu
        String namaPeminjam, namaRuangan, kebutuhan, tanggalPinjam, waktuPinjam, kapasitasPinjam, tanggalDibuat, idPeminjaman, status;
        if(currID.equals(idPeminjam)){  //kalau data ini milik si user maka tampilkan di field agar bisa diubah
            idPeminjam = tabelMahasiswa.getValueAt(baris, 1).toString();
            idPeminjamField.setText(idPeminjam);
            namaPeminjam = tabelMahasiswa.getValueAt(baris, 2).toString();
            namaPeminjamField.setText(namaPeminjam);
            namaRuangan = tabelMahasiswa.getValueAt(baris, 4).toString();
            namaRuanganCombo.setSelectedItem(namaRuangan);
            kebutuhan = tabelMahasiswa.getValueAt(baris, 7).toString();
            kebutuhanField.setText(kebutuhan);
            tanggalPinjam = tabelMahasiswa.getValueAt(baris, 5).toString();
            tanggalPinjamField.setText(tanggalPinjam);
            waktuPinjam = tabelMahasiswa.getValueAt(baris, 6).toString();
            waktuPinjamField.setText(waktuPinjam);
            kapasitasPinjam = tabelMahasiswa.getValueAt(baris, 8).toString();
            kapasitasPinjamField.setText(kapasitasPinjam);
            tanggalDibuat = tabelMahasiswa.getValueAt(baris, 3).toString();
            tanggalDibuatField.setText(tanggalDibuat);
            idPeminjaman = tabelMahasiswa.getValueAt(baris, 0).toString();
            idPeminjamanField.setText(idPeminjaman);
            status = tabelMahasiswa.getValueAt(baris, 9).toString();
            statusField.setText(status);
        }
        else{
            kosong();
        }
    }//GEN-LAST:event_tabelMahasiswaMouseClicked

    private void exitMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMenuMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMenuMouseClicked

    public void load_table(){
        //membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel(){
            public boolean isCellEditable(int rowIndex, int colIndex) 
            {
                return false;
            }
        };
        model.addColumn("ID Peminjaman");
        model.addColumn("ID Peminjam");
        model.addColumn("Nama Peminjam");
        model.addColumn("Tanggal Post");
        model.addColumn("Nama Ruangan");
        model.addColumn("Tanggal Pinjam");
        model.addColumn("Waktu Pinjam");
        model.addColumn("Kebutuhan Pinjam");
        model.addColumn("Kapasitas Pinjam");
        model.addColumn("Status");
        
        //String id_peminjaman,id_peminjam,nama_peminjam,tgl_post,nama_ruangan,tgl_pinjam,waktu_pinjam,kebutuhan_pinjam,kapasitas_pinjam;
        
        //menampilkan data database ke dalam tabel
        try{
            //int no=1;
            String sql = "SELECT * FROM t_peminjaman";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),
                    res.getString(2),res.getString(3),res.getString(4),
                    res.getString(5),res.getString(6),res.getString(7)
                    ,res.getString(8),res.getString(9),res.getString(10)});
            }
            tabelMahasiswa.setModel(model);
        }
        catch (Exception e){
            
        }
    }
    
    public void tampil_combo()
    {
        try {
            String sql = "SELECT nama_ruangan FROM t_ruangan order by kd_ruangan asc";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
        
            while(res.next()){
                Object[] ob = new Object[3];
                ob[0] = res.getString(1);

                namaRuanganCombo.addItem((String) ob[0]);// fungsi ini bertugas menampung isi dari database
            }
            res.close(); stm.close();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }
    
    private void kosong(){
        //DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
        Date date = new Date();
        tanggalDibuatField.setText(dateFormat.format(date));
        namaRuanganCombo.setSelectedItem("-- Pilih --");
        kebutuhanField.setText(null);
        tanggalPinjamField.setText(null);
        waktuPinjamField.setText(null);
        kapasitasPinjamField.setText(null);
        idPeminjamanField.setText(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buat_Permohonan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buat_Permohonan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buat_Permohonan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buat_Permohonan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buat_Permohonan().setVisible(true);
                
        //bikin menu bar
        //menuBar = new JMenuBar();

        //Build the first menu.
        //menu = new JMenu("A Menu");
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JButton editButton;
    private javax.swing.JMenu exitMenu;
    private javax.swing.JTextField idPeminjamField;
    private javax.swing.JLabel idPeminjamLabel;
    private javax.swing.JTextField idPeminjamanField;
    private javax.swing.JLabel idPeminjamanLabel;
    private javax.swing.JOptionPane jOptionPane2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kapasitasPinjamField;
    private javax.swing.JLabel kapasitasPinjamLabel;
    private javax.swing.JTextField kebutuhanField;
    private javax.swing.JLabel kebutuhanLabel;
    private javax.swing.JMenu lihatPeminjamanMenu;
    private javax.swing.JMenuBar mahasiswaMenuBar;
    private javax.swing.JTextField namaPeminjamField;
    private javax.swing.JLabel namaPeminjamLabel;
    private javax.swing.JComboBox<String> namaRuanganCombo;
    private javax.swing.JLabel namaRuanganLabel;
    private javax.swing.JTextField statusField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTable tabelMahasiswa;
    private javax.swing.JButton tambahButton;
    private javax.swing.JTextField tanggalDibuatField;
    private javax.swing.JLabel tanggalDibuatLabel;
    private javax.swing.JTextField tanggalPinjamField;
    private javax.swing.JLabel tanggalPinjamLabel;
    private javax.swing.JTextField waktuPinjamField;
    private javax.swing.JLabel waktuPinjamLabel;
    // End of variables declaration//GEN-END:variables
}
