/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sipijar;

import java.sql.Connection;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rifaldo
 */
public class DataRuangan extends javax.swing.JFrame {

    /**
     * Creates new form DataUser
     */
    public DataRuangan() {
        initComponents();
        
        load_table();
    }
        
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        dataRuanganPanel = new javax.swing.JPanel();
        dataRuanganScroll = new javax.swing.JScrollPane();
        dataRuanganTable = new javax.swing.JTable();
        baruButton = new javax.swing.JButton();
        simpanButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        hapusButton = new javax.swing.JButton();
        kodeRuanganLabel = new javax.swing.JLabel();
        kodeRuanganField = new javax.swing.JTextField();
        namaRuanganLabel = new javax.swing.JLabel();
        namaRuanganField = new javax.swing.JTextField();
        kapasitasLabel = new javax.swing.JLabel();
        kapasitasField = new javax.swing.JTextField();
        dataUserMenuBar = new javax.swing.JMenuBar();
        kembaliMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        dataRuanganPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(128, 128, 128)), "Data Ruangan"));
        dataRuanganPanel.setPreferredSize(new java.awt.Dimension(780, 270));

        dataRuanganTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataRuanganTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataRuanganTableMouseClicked(evt);
            }
        });
        dataRuanganScroll.setViewportView(dataRuanganTable);

        baruButton.setText("Baru");
        baruButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baruButtonActionPerformed(evt);
            }
        });

        simpanButton.setText("Tambah");
        simpanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanButtonActionPerformed(evt);
            }
        });

        editButton.setText("Update");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        hapusButton.setText("Hapus");
        hapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusButtonActionPerformed(evt);
            }
        });

        kodeRuanganLabel.setText("Kode Ruangan");

        namaRuanganLabel.setText("Nama Ruangan");

        kapasitasLabel.setText("Kapasitas");

        javax.swing.GroupLayout dataRuanganPanelLayout = new javax.swing.GroupLayout(dataRuanganPanel);
        dataRuanganPanel.setLayout(dataRuanganPanelLayout);
        dataRuanganPanelLayout.setHorizontalGroup(
            dataRuanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataRuanganPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataRuanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(baruButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(simpanButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hapusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(dataRuanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataRuanganPanelLayout.createSequentialGroup()
                        .addComponent(kodeRuanganLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kodeRuanganField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(namaRuanganLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(namaRuanganField, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(kapasitasLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kapasitasField, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataRuanganPanelLayout.createSequentialGroup()
                        .addComponent(dataRuanganScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        dataRuanganPanelLayout.setVerticalGroup(
            dataRuanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataRuanganPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(dataRuanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(baruButton)
                    .addComponent(kodeRuanganLabel)
                    .addComponent(kodeRuanganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaRuanganLabel)
                    .addComponent(namaRuanganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kapasitasLabel)
                    .addComponent(kapasitasField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(dataRuanganPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataRuanganPanelLayout.createSequentialGroup()
                        .addComponent(simpanButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hapusButton))
                    .addComponent(dataRuanganScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(250, 250, 250))
        );

        kembaliMenu.setText("Kembali");
        kembaliMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMenuMouseClicked(evt);
            }
        });
        kembaliMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliMenuActionPerformed(evt);
            }
        });
        dataUserMenuBar.add(kembaliMenu);

        setJMenuBar(dataUserMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataRuanganPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 815, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataRuanganPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliMenuActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_kembaliMenuActionPerformed

    private void kembaliMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMenuMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_kembaliMenuMouseClicked

    private void dataRuanganTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataRuanganTableMouseClicked
        //menampilkan data ke dalam form pengisian
        int baris = dataRuanganTable.rowAtPoint(evt.getPoint());
        //String currID = idPeminjamField.getText();
        //String idPeminjam = tabelMahasiswa.getValueAt(baris, 1).toString();
        String kode_ruangan, nama_ruangan, kapasitas;
        kode_ruangan = dataRuanganTable.getValueAt(baris, 0).toString();
        kodeRuanganField.setText(kode_ruangan);
        nama_ruangan = dataRuanganTable.getValueAt(baris, 1).toString();
        namaRuanganField.setText(nama_ruangan);
        kapasitas = dataRuanganTable.getValueAt(baris, 2).toString();
        kapasitasField.setText(kapasitas);
    }//GEN-LAST:event_dataRuanganTableMouseClicked

    private void baruButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baruButtonActionPerformed
        kosong();
    }//GEN-LAST:event_baruButtonActionPerformed

    private void simpanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanButtonActionPerformed
        try{
            String sql = "INSERT INTO t_ruangan (kd_ruangan,nama_ruangan,kapasitas) VALUES ('"+
                    kodeRuanganField.getText()+"','"+namaRuanganField.getText()+"','"+kapasitasField.getText()+"')";
            java.sql.Connection conn = (Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            //java.util.Date now = new java.util.Date();
            //pst.setDate( 3, new java.sql.Date( now.getTime() ) );
            pst.execute();
            jOptionPane1.showMessageDialog(null, "Tambah Data Berhasil");
            load_table();
            kosong();
            pst.close();
            conn.close();
        } 
        catch (Exception e) {
            jOptionPane1.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_simpanButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        try{
            String sql = "UPDATE t_ruangan SET kd_ruangan = '"+kodeRuanganField.getText()+"',"+
                    " nama_ruangan = '"+namaRuanganField.getText()+"',"+
                    " kapasitas = '"+kapasitasField.getText()+"'"+
                    " WHERE kd_ruangan = '"+kodeRuanganField.getText()+"'";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            jOptionPane1.showMessageDialog(null, "Data Berhasil Diedit");
            
            pst.close();
            conn.close();
        }
        catch(Exception e){
            jOptionPane1.showMessageDialog(null, "Perubahan Data Gagal "+e.getMessage());
        }
        load_table();
        kosong();
    }//GEN-LAST:event_editButtonActionPerformed

    private void hapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusButtonActionPerformed
        JDialog.setDefaultLookAndFeelDecorated(true);
        int response = jOptionPane1.showConfirmDialog(null, "Yakin ingin menghapus?", "Konfirmasi",
            jOptionPane1.YES_NO_OPTION, jOptionPane1.QUESTION_MESSAGE);
        if (response == jOptionPane1.YES_OPTION) {
            try{
                String sql = "DELETE FROM t_ruangan WHERE kd_ruangan= '"+kodeRuanganField.getText()+"'";
                java.sql.Connection conn = (Connection)Config.configDB();
                java.sql.PreparedStatement pst=conn.prepareStatement(sql);
                pst.execute();
                load_table();
                kosong();
                jOptionPane1.showMessageDialog(null, "Hapus Data Berhasil");
            } 
            catch (Exception e) {
                jOptionPane1.showMessageDialog(this, e.getMessage());
            }
        }
    }//GEN-LAST:event_hapusButtonActionPerformed

    public void load_table(){
        //membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel(){
            public boolean isCellEditable(int rowIndex, int colIndex) 
            {
                return false;
            }
        };
        model.addColumn("Kode Ruangan");
        model.addColumn("Nama Ruangan");
        model.addColumn("Kapasitas");
        
        //menampilkan data database ke dalam tabel
        try{
            String sql = "SELECT kd_ruangan,nama_ruangan,kapasitas FROM t_ruangan";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),
                    res.getString(2),res.getString(3)});
            }
            dataRuanganTable.setModel(model);
        }
        catch (Exception e){
            
        }
    }
    
    private void kosong(){
        kodeRuanganField.setText(null);
        namaRuanganField.setText(null);
        kapasitasField.setText(null);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataRuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataRuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataRuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataRuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataRuangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baruButton;
    private javax.swing.JPanel dataRuanganPanel;
    private javax.swing.JScrollPane dataRuanganScroll;
    private javax.swing.JTable dataRuanganTable;
    private javax.swing.JMenuBar dataUserMenuBar;
    private javax.swing.JButton editButton;
    private javax.swing.JButton hapusButton;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JTextField kapasitasField;
    private javax.swing.JLabel kapasitasLabel;
    private javax.swing.JMenu kembaliMenu;
    private javax.swing.JTextField kodeRuanganField;
    private javax.swing.JLabel kodeRuanganLabel;
    private javax.swing.JTextField namaRuanganField;
    private javax.swing.JLabel namaRuanganLabel;
    private javax.swing.JButton simpanButton;
    // End of variables declaration//GEN-END:variables
}
