/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sipijar;

import java.sql.Connection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rifaldo
 */
public class DataUser extends javax.swing.JFrame {

    /**
     * Creates new form DataUser
     */
    public DataUser() {
        initComponents();
        
        load_table();
    }
        
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataMahasiswaPanel = new javax.swing.JPanel();
        dataMahasiswaScroll = new javax.swing.JScrollPane();
        dataMahasiswaTable = new javax.swing.JTable();
        dataKemahasiswaanPanel = new javax.swing.JPanel();
        dataKemahasiswaanScroll = new javax.swing.JScrollPane();
        dataKemahasiswaanTable = new javax.swing.JTable();
        dataUserMenuBar = new javax.swing.JMenuBar();
        kembaliMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(800, 600));

        dataMahasiswaPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(128, 128, 128)), "Data Mahasiswa"));
        dataMahasiswaPanel.setPreferredSize(new java.awt.Dimension(780, 270));

        dataMahasiswaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataMahasiswaScroll.setViewportView(dataMahasiswaTable);

        javax.swing.GroupLayout dataMahasiswaPanelLayout = new javax.swing.GroupLayout(dataMahasiswaPanel);
        dataMahasiswaPanel.setLayout(dataMahasiswaPanelLayout);
        dataMahasiswaPanelLayout.setHorizontalGroup(
            dataMahasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataMahasiswaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataMahasiswaScroll)
                .addContainerGap())
        );
        dataMahasiswaPanelLayout.setVerticalGroup(
            dataMahasiswaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataMahasiswaPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dataMahasiswaScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        dataKemahasiswaanPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(128, 128, 128)), "Data Kemahasiswaan"));
        dataKemahasiswaanPanel.setPreferredSize(new java.awt.Dimension(0, 270));

        dataKemahasiswaanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dataKemahasiswaanScroll.setViewportView(dataKemahasiswaanTable);

        javax.swing.GroupLayout dataKemahasiswaanPanelLayout = new javax.swing.GroupLayout(dataKemahasiswaanPanel);
        dataKemahasiswaanPanel.setLayout(dataKemahasiswaanPanelLayout);
        dataKemahasiswaanPanelLayout.setHorizontalGroup(
            dataKemahasiswaanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataKemahasiswaanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataKemahasiswaanScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
                .addContainerGap())
        );
        dataKemahasiswaanPanelLayout.setVerticalGroup(
            dataKemahasiswaanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dataKemahasiswaanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataKemahasiswaanScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addContainerGap())
        );

        kembaliMenu.setText("Kembali");
        kembaliMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMenuMouseClicked(evt);
            }
        });
        kembaliMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliMenuActionPerformed(evt);
            }
        });
        dataUserMenuBar.add(kembaliMenu);

        setJMenuBar(dataUserMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataMahasiswaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dataKemahasiswaanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dataMahasiswaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(dataKemahasiswaanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliMenuActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_kembaliMenuActionPerformed

    private void kembaliMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMenuMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_kembaliMenuMouseClicked

    public void load_table(){
        //membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel(){
            public boolean isCellEditable(int rowIndex, int colIndex) 
            {
                return false;
            }
        };
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Kelas");
        model.addColumn("Prodi");
        model.addColumn("No. HP");
        model.addColumn("Alamat E-mail");
        
        //menampilkan data database ke dalam tabel
        try{
            //int no=1;
            String sql = "SELECT id,nama,kelas,prodi,nohp,email FROM t_mahasiswa";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),
                    res.getString(2),res.getString(3),
                    res.getString(4),res.getString(5),res.getString(6)});
            }
            dataMahasiswaTable.setModel(model);
        }
        catch (Exception e){
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DataUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel dataKemahasiswaanPanel;
    private javax.swing.JScrollPane dataKemahasiswaanScroll;
    private javax.swing.JTable dataKemahasiswaanTable;
    private javax.swing.JPanel dataMahasiswaPanel;
    private javax.swing.JScrollPane dataMahasiswaScroll;
    private javax.swing.JTable dataMahasiswaTable;
    private javax.swing.JMenuBar dataUserMenuBar;
    private javax.swing.JMenu kembaliMenu;
    // End of variables declaration//GEN-END:variables
}
