/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sipijar;

import java.sql.Connection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rifaldo
 */
public class Persetujuan_Permohonan extends javax.swing.JFrame {

    /**
     * Creates new form Kemahasiswaan
     */
    public Persetujuan_Permohonan() {
        initComponents();
    }
    
    public Persetujuan_Permohonan(String passid,String passnama){
        initComponents();
        
        idField.setText(passid);
        namaField.setText(passnama);
        //System.out.println(dateFormat.format(date)); //2018/12/07
        load_table();
    }
    /*public Kemahasiswaan(String passid,String passnama){
        initComponents();
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane = new javax.swing.JOptionPane();
        jPanel1 = new javax.swing.JPanel();
        idPeminjamLabel = new javax.swing.JLabel();
        idPeminjamField = new javax.swing.JTextField();
        kebutuhanLabel = new javax.swing.JLabel();
        kebutuhanField = new javax.swing.JTextField();
        tanggalPinjamLabel = new javax.swing.JLabel();
        tanggalPinjamField = new javax.swing.JTextField();
        waktuPinjamLabel = new javax.swing.JLabel();
        waktuPinjamField = new javax.swing.JTextField();
        kapasitasPinjamLabel = new javax.swing.JLabel();
        kapasitasPinjamField = new javax.swing.JTextField();
        tanggalDibuatLabel = new javax.swing.JLabel();
        tanggalDibuatField = new javax.swing.JTextField();
        idPeminjamanLabel = new javax.swing.JLabel();
        idPeminjamanField = new javax.swing.JTextField();
        namaPeminjamLabel = new javax.swing.JLabel();
        namaPeminjamField = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();
        statusCombo = new javax.swing.JComboBox<>();
        simpanBtn = new javax.swing.JButton();
        namaRuanganLabel = new javax.swing.JLabel();
        namaRuanganField = new javax.swing.JTextField();
        kemahasiswaanPanel = new javax.swing.JPanel();
        idLabel = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        namaLabel = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listPermohonanTable = new javax.swing.JTable();
        kemahasiswaanMenuBar = new javax.swing.JMenuBar();
        persetujuanPermohonanMenu = new javax.swing.JMenu();
        dataRuangan = new javax.swing.JMenu();
        exitMenu = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIPIJAR - Persetujuan Permohonan Peminjaman Ruangan");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(128, 128, 128)), "List Permohonan Peminjaman Ruangan", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18))); // NOI18N
        jPanel1.setForeground(java.awt.Color.lightGray);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 450));

        idPeminjamLabel.setText("ID Peminjam");

        idPeminjamField.setEditable(false);
        idPeminjamField.setBackground(new java.awt.Color(204, 204, 204));
        idPeminjamField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPeminjamFieldActionPerformed(evt);
            }
        });

        kebutuhanLabel.setText("Kebutuhan");

        kebutuhanField.setEditable(false);
        kebutuhanField.setBackground(new java.awt.Color(204, 204, 204));

        tanggalPinjamLabel.setText("Tanggal Dipinjam");

        tanggalPinjamField.setEditable(false);
        tanggalPinjamField.setBackground(new java.awt.Color(204, 204, 204));

        waktuPinjamLabel.setText("Waktu Pinjam");

        waktuPinjamField.setEditable(false);
        waktuPinjamField.setBackground(new java.awt.Color(204, 204, 204));

        kapasitasPinjamLabel.setText("Kapasitas Pinjam");

        kapasitasPinjamField.setEditable(false);
        kapasitasPinjamField.setBackground(new java.awt.Color(204, 204, 204));

        tanggalDibuatLabel.setText("Tanggal Dibuat");

        tanggalDibuatField.setEditable(false);
        tanggalDibuatField.setBackground(new java.awt.Color(204, 204, 204));

        idPeminjamanLabel.setText("ID Peminjaman");

        idPeminjamanField.setEditable(false);
        idPeminjamanField.setBackground(new java.awt.Color(204, 204, 204));

        namaPeminjamLabel.setText("Nama Peminjam");

        namaPeminjamField.setEditable(false);
        namaPeminjamField.setBackground(new java.awt.Color(204, 204, 204));

        statusLabel.setText("Status");

        statusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Belum Disetujui", "Disetujui" }));

        simpanBtn.setText("Simpan");
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });

        namaRuanganLabel.setText("Nama Ruangan");

        namaRuanganField.setEditable(false);
        namaRuanganField.setBackground(new java.awt.Color(204, 204, 204));

        kemahasiswaanPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(128, 128, 128)));

        idLabel.setText("ID Anda");

        idField.setEditable(false);
        idField.setBackground(new java.awt.Color(204, 204, 204));

        namaLabel.setText("Nama Anda");

        namaField.setEditable(false);
        namaField.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout kemahasiswaanPanelLayout = new javax.swing.GroupLayout(kemahasiswaanPanel);
        kemahasiswaanPanel.setLayout(kemahasiswaanPanelLayout);
        kemahasiswaanPanelLayout.setHorizontalGroup(
            kemahasiswaanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kemahasiswaanPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(idLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(namaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
        kemahasiswaanPanelLayout.setVerticalGroup(
            kemahasiswaanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kemahasiswaanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kemahasiswaanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kemahasiswaanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(namaLabel)
                        .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kemahasiswaanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idLabel)
                        .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        listPermohonanTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listPermohonanTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listPermohonanTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listPermohonanTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(kemahasiswaanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(idPeminjamanLabel)
                                .addGap(35, 35, 35)
                                .addComponent(idPeminjamanField, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(namaRuanganLabel)
                                        .addComponent(idPeminjamLabel)
                                        .addComponent(tanggalPinjamLabel))
                                    .addComponent(kapasitasPinjamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(kapasitasPinjamField)
                                    .addComponent(tanggalPinjamField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaRuanganField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idPeminjamField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(namaPeminjamLabel)
                                .addGap(9, 9, 9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(waktuPinjamLabel)
                                    .addComponent(kebutuhanLabel)
                                    .addComponent(tanggalDibuatLabel)
                                    .addComponent(statusLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namaPeminjamField, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(simpanBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tanggalDibuatField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(waktuPinjamField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kebutuhanField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(68, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kemahasiswaanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idPeminjamLabel)
                            .addComponent(idPeminjamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(tanggalPinjamLabel)
                                .addComponent(tanggalPinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(namaRuanganField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(namaRuanganLabel))
                                .addGap(26, 26, 26)))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kapasitasPinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kapasitasPinjamLabel)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namaPeminjamLabel)
                            .addComponent(namaPeminjamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kebutuhanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kebutuhanLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(waktuPinjamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(waktuPinjamLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tanggalDibuatLabel)
                            .addComponent(tanggalDibuatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(statusCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(statusLabel))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idPeminjamanField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idPeminjamanLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(simpanBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE))
        );

        persetujuanPermohonanMenu.setText("Persetujuan Permohonan");
        kemahasiswaanMenuBar.add(persetujuanPermohonanMenu);

        dataRuangan.setText("Data Ruangan");
        dataRuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataRuanganMouseClicked(evt);
            }
        });
        dataRuangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataRuanganActionPerformed(evt);
            }
        });
        kemahasiswaanMenuBar.add(dataRuangan);

        exitMenu.setText("Exit");
        exitMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMenuMouseClicked(evt);
            }
        });
        kemahasiswaanMenuBar.add(exitMenu);

        setJMenuBar(kemahasiswaanMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void listPermohonanTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listPermohonanTableMouseClicked
        //menampilkan data ke dalam form pengisian
        int baris = listPermohonanTable.rowAtPoint(evt.getPoint());
        
        String idPeminjam, namaPeminjam, namaRuangan, kebutuhan, tanggalPinjam, waktuPinjam, kapasitasPinjam, tanggalDibuat, idPeminjaman, status;
        
        idPeminjam = listPermohonanTable.getValueAt(baris, 1).toString();
        idPeminjamField.setText(idPeminjam);
        namaPeminjam = listPermohonanTable.getValueAt(baris, 2).toString();
        namaPeminjamField.setText(namaPeminjam);
        namaRuangan = listPermohonanTable.getValueAt(baris, 4).toString();
        namaRuanganField.setText(namaRuangan);
        kebutuhan = listPermohonanTable.getValueAt(baris, 7).toString();
        kebutuhanField.setText(kebutuhan);
        tanggalPinjam = listPermohonanTable.getValueAt(baris, 5).toString();
        tanggalPinjamField.setText(tanggalPinjam);
        waktuPinjam = listPermohonanTable.getValueAt(baris, 6).toString();
        waktuPinjamField.setText(waktuPinjam);
        kapasitasPinjam = listPermohonanTable.getValueAt(baris, 8).toString();
        kapasitasPinjamField.setText(kapasitasPinjam);
        tanggalDibuat = listPermohonanTable.getValueAt(baris, 3).toString();
        tanggalDibuatField.setText(tanggalDibuat);
        idPeminjaman = listPermohonanTable.getValueAt(baris, 0).toString();
        idPeminjamanField.setText(idPeminjaman);
        status = listPermohonanTable.getValueAt(baris, 9).toString();
        statusCombo.setSelectedItem(status);
    }//GEN-LAST:event_listPermohonanTableMouseClicked

    private void idPeminjamFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPeminjamFieldActionPerformed
        
    }//GEN-LAST:event_idPeminjamFieldActionPerformed

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanBtnActionPerformed
        try{
            //UPDATE `members` SET `contact_number` = '0759 253 542' WHERE `membership_number` = 1;
            String sql = "UPDATE t_peminjaman SET status = '"+statusCombo.getSelectedItem()+"'"+
                    " WHERE id_peminjaman = '"+idPeminjamanField.getText()+"'";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            jOptionPane.showMessageDialog(null, "Data Berhasil Diedit");
            
            pst.close();
            conn.close();
        }
        catch(Exception e){
            jOptionPane.showMessageDialog(null, "Perubahan Data Gagal "+e.getMessage());
        }
        load_table();
    }//GEN-LAST:event_simpanBtnActionPerformed

    private void exitMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMenuMouseClicked
        System.exit(0);
    }//GEN-LAST:event_exitMenuMouseClicked

    private void dataRuanganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataRuanganActionPerformed
        
    }//GEN-LAST:event_dataRuanganActionPerformed

    private void dataRuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataRuanganMouseClicked
        new DataRuangan().setVisible(true);
    }//GEN-LAST:event_dataRuanganMouseClicked

    public void load_table(){
        //membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel(){
            public boolean isCellEditable(int rowIndex, int colIndex) 
            {
                return false;
            }
        };
        model.addColumn("ID Peminjaman");
        model.addColumn("ID Peminjam");
        model.addColumn("Nama Peminjam");
        model.addColumn("Tanggal Post");
        model.addColumn("Nama Ruangan");
        model.addColumn("Tanggal Pinjam");
        model.addColumn("Waktu Pinjam");
        model.addColumn("Kebutuhan Pinjam");
        model.addColumn("Kapasitas Pinjam");
        model.addColumn("Status");
        
        //String id_peminjaman,id_peminjam,nama_peminjam,tgl_post,nama_ruangan,tgl_pinjam,waktu_pinjam,kebutuhan_pinjam,kapasitas_pinjam;
        
        //menampilkan data database ke dalam tabel
        try{
            //int no=1;
            String sql = "SELECT * FROM t_peminjaman";
            java.sql.Connection conn=(Connection)Config.configDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
            
            while(res.next()){
                model.addRow(new Object[]{res.getString(1),
                    res.getString(2),res.getString(3),res.getString(4),
                    res.getString(5),res.getString(6),res.getString(7)
                    ,res.getString(8),res.getString(9),res.getString(10)});
            }
            listPermohonanTable.setModel(model);
        }
        catch (Exception e){
            
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Persetujuan_Permohonan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Persetujuan_Permohonan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Persetujuan_Permohonan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Persetujuan_Permohonan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Persetujuan_Permohonan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu dataRuangan;
    private javax.swing.JMenu exitMenu;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JTextField idPeminjamField;
    private javax.swing.JLabel idPeminjamLabel;
    private javax.swing.JTextField idPeminjamanField;
    private javax.swing.JLabel idPeminjamanLabel;
    private javax.swing.JOptionPane jOptionPane;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kapasitasPinjamField;
    private javax.swing.JLabel kapasitasPinjamLabel;
    private javax.swing.JTextField kebutuhanField;
    private javax.swing.JLabel kebutuhanLabel;
    private javax.swing.JMenuBar kemahasiswaanMenuBar;
    private javax.swing.JPanel kemahasiswaanPanel;
    private javax.swing.JTable listPermohonanTable;
    private javax.swing.JTextField namaField;
    private javax.swing.JLabel namaLabel;
    private javax.swing.JTextField namaPeminjamField;
    private javax.swing.JLabel namaPeminjamLabel;
    private javax.swing.JTextField namaRuanganField;
    private javax.swing.JLabel namaRuanganLabel;
    private javax.swing.JMenu persetujuanPermohonanMenu;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JComboBox<String> statusCombo;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField tanggalDibuatField;
    private javax.swing.JLabel tanggalDibuatLabel;
    private javax.swing.JTextField tanggalPinjamField;
    private javax.swing.JLabel tanggalPinjamLabel;
    private javax.swing.JTextField waktuPinjamField;
    private javax.swing.JLabel waktuPinjamLabel;
    // End of variables declaration//GEN-END:variables
}
